### ISSUE TITLE
oauth2.0

### ISSUE THREAD

**Issue by authub** [artemMartynenko/spring-cloud-gateway-oauth2-sso-sample-application#5]
Hello, can I build an oauth2.0 server to start and access locally? Thank you

**Comment by artemMartynenko** [comment]
This sample application mostly adopted for custom (self owned ) oauth2.0 server. There are a lot of examples of spring based oauth servers. but if it is really need and can be helpful, i can add example of oauth server as project module for providing of complete example.

**Comment by cyjnz** [comment]
Yes, I also need. Thank you
