### ISSUE TITLE
oauth2.0-2

### ISSUE THREAD

**Issue by authub** [artemMartynenko/spring-cloud-gateway-oauth2-sso-sample-application#6]
I look forward to your integration of oauth2.0 with spring gateway.

**Comment by authub** [comment]
The last question was closed by me. Sorry, so I created a new one.

**Comment by RajasGujarathi** [comment]
Is Spring cloud gateway supporting Oauth2 because I am unable to proceed. Also this code is not working for me, any help will be much appreciated. 
![Capture](https://user-images.githubusercontent.com/31616516/64174273-364df280-ce59-11e9-8c9f-1c421dfb81ae.PNG)
